# Generated by Django 4.2.17 on 2026-01-29 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_quiz_max_attempts'),
        ('courses', '0004_add_coursegradingconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='required_quiz',
            field=models.ForeignKey(blank=True, help_text='Quiz that must be passed to complete this lesson', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='required_for_lessons', to='quizzes.quiz'),
        ),
    ]
