# Generated by Django 4.2.17 on 2026-01-29 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_add_lesson_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonquestionanswer',
            name='selected_choice',
            field=models.ForeignKey(help_text='Set to NULL if choice is deleted (e.g., when question is edited)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selections', to='courses.lessonquestionchoice'),
        ),
    ]
