# Generated by Django 4.2.17 on 2026-01-29 03:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0007_fix_answer_cascade_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='max_quiz_attempts',
            field=models.PositiveIntegerField(default=0, help_text='Maximum attempts for comprehension quiz (0 = unlimited)'),
        ),
        migrations.CreateModel(
            name='LessonQuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('score', models.PositiveIntegerField(help_text='Number of correct answers')),
                ('total_questions', models.PositiveIntegerField()),
                ('passed', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='courses.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'courses_lessonquizattempt',
                'ordering': ['-attempt_number'],
                'unique_together': {('user', 'lesson', 'attempt_number')},
            },
        ),
    ]
