# Generated by Django 4.2.17 on 2026-01-29 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_add_quiz_attempts'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='lesson_attachments/%Y/%m/')),
                ('filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(help_text='File type/extension', max_length=50)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='courses.lesson')),
            ],
            options={
                'db_table': 'courses_lessonattachment',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
