# Generated by Django 4.2.17 on 2026-01-30 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_add_instructor_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorreminder',
            name='end_time',
            field=models.TimeField(blank=True, help_text='End time (optional)', null=True),
        ),
        migrations.AlterField(
            model_name='instructorreminder',
            name='time',
            field=models.TimeField(blank=True, help_text='Start time', null=True),
        ),
    ]
